### ISSUE TITLE
Tag/release zycore-c?

### ISSUE THREAD

**Issue by ccotter** [zyantific/zycore-c#22]
Hi - I am building zydis, which depends on zycore-c. The internal packaging tool I'm using works nicely when there are *versioned* releases of the source code - in particular, where there are "official" tagged versioned releases, which github.com will offer as tar.gz (otherwise, I have to create my own versioning scheme). Could you provide tags/releases for zycore-c, similar to what is setup for [zydis's releases](https://github.com/zyantific/zydis/releases)?

thanks!

**Comment by athre0z** [comment]
Thanks for creating the issue and sorry for the delay!

I have now `v1.0.0` tagged the commit used in the latest Zydis release (as of writing: `v3.1.0`):
https://github.com/zyantific/zycore-c/releases/tag/v1.0.0
