### ISSUE TITLE
typo in ifdef in Types.h

### ISSUE THREAD

**Issue by npatil2** [zyantific/zycore-c#23]
I ran into a compile error trying to compile zydis on an old linux machine.  I think the reason is the typo fixed by the diff below. The typo causes even regular linux compiles to use compiler-builtin versions of types instead of the stdint versions.  (For some reason, my older machine doesn't have \_\_UINT8_TYPE__ variants, despite using gcc-9.2, so I actually _need_ to use the stdint versions.)

```
diff --git a/include/Zycore/Types.h b/include/Zycore/Types.h
index b844d1d..7e7e934 100644
--- a/include/Zycore/Types.h
+++ b/include/Zycore/Types.h
@@ -39,7 +39,7 @@
 /* ============================================================================================== */
 
 #if !defined(ZYAN_NO_LIBC) && \
-    (!defined(ZYAN_MSVC) && defined(ZYAN_KERNEL)) // The WDK LibC lacks stdint.h.
+    !(defined(ZYAN_MSVC) && defined(ZYAN_KERNEL)) // The WDK LibC lacks stdint.h.
     // If is LibC present, we use stdint types.
 #   include <stdint.h>
 #   include <stddef.h>

```

**Comment by athre0z** [comment]
Thanks for creating this issue and root causing it! That indeed looks the `!` snuck on the wrong side of the parentheses for this one. I'll commit your patch later today.
