### ISSUE TITLE
Support in linux kernel 5.4

### ISSUE THREAD

**Issue by Tsn0w** [zyantific/zycore-c#25]
Hi :)
I'm using your ZYDIS in my LKM and therefore zycore-c submodule, and since kernel 5.4 (using gcc >7), I'm receiving the following error:

```
./include/linux/compiler_attributes.h:200:41: error: expected ‘)’ before ‘__attribute__’
  200 | # define fallthrough                    __attribute__((__fallthrough__))
      |                                         ^~~~~~~~~~~~~
/home/chameleon/mlp.main/mlp.kernel/main-module/include/Zycore/Defines.h:246:45: note: in expansion of macro ‘fallthrough’
  246 | #   define ZYAN_FALLTHROUGH __attribute__ ((fallthrough))
      |                                             ^~~~~~~~~~~
/home/chameleon/mlp.main/mlp.kernel/main-module/repos/zydis/src/Decoder.c:2617:17: note: in expansion of macro ‘ZYAN_FALLTHROUGH’
 2617 |                 ZYAN_FALLTHROUGH;
      |                 ^~~~~~~~~~~~~~~~

```

Now, after some research it seems that the problem was due the fact that in kernel 5.4 [this commit](https://github.com/torvalds/linux/commit/294f69e662d1570703e9b56e95be37a9fd3afba5) inserted a fallthrough define.
[the same issue was at vbox](https://www.virtualbox.org/ticket/18945?cversion=0&cnum_hist=16#comment:7) 
And after testing, the solution was replace the 
```
#   define ZYAN_FALLTHROUGH __attribute__ ((fallthrough))
```
to 
```
#   define ZYAN_FALLTHROUGH __attribute__ ((__fallthrough__))
```

Can you apply this change?

Many thanks

**Comment by flobernd** [comment]
Hey there,

I will have a look. Need to check if this change does have any side effects with different compiler versions.

**Comment by Tsn0w** [comment]
Thanks for answer :)

I've tried this with gcc version 7,8,9 and seems to work fine.
Is there any other tests I can do to validate?
If you want I can make a PR on this change

**Comment by flobernd** [comment]
That sounds promising :-) A PR is always appreciated!

**Comment by athre0z** [comment]
I checked this on godbolt.org earlier today, and interestingly enough, despite there being no documentation on it, the variant with the additional underscores seems to work fine for all GCC versions in our ifdef filter (>= 7), so we should be good to go with that. :-)

On a related side note, [C23 adds `[[fallthrough]]`](https://en.cppreference.com/w/c/language/attributes/fallthrough) to the standard, so we might be able to just use that in a few years.

**Comment by flobernd** [comment]
Thanks for the PR. I just merged it and will bump the `zycore-c` dependency of `zydis` later today.

Solved with https://github.com/zyantific/zycore-c/pull/26
