### ISSUE TITLE
Please consider tagging releases

### ISSUE THREAD

**Issue by Tachi107** [zyantific/zycore-c#37]
Hi, I know Zycore is mainly used as an internal library of some Zyantific projects (like Zydis), so working with releases for this library is not really that useful to you, but while maintaining the [Zydis Debian package](https://packages.debian.org/unstable/libzydis-dev) (that is now in Debian Unstable :D) I noticed that Zydis requires some features not present in Zycore 1.0.0, so I have to manually backport every change you make to Zycore that is also used in Zydis. 

This is quite laborious and error prone, since with these backports I just aim at making the compiler happy - some behavioral changes and security fixes will certainly be missed, and Debian could end up having a Zydis library that depends on a buggy/unsafe Zycore, resulting in a buggy/unsafe Zydis.

Debian packages should be built from stable releases, so I can't just package the latest master (well, I could, but it is highly discouraged, and creates some issues like the impossibility of applying security fixes to packages in Debian stable, as they can't receive feature updates).

While certainly handy, I'm not asking for API or ABI stability, just some way to make sure that Zydis can be safely built from a tagged release - downstream and upstream should always collaborate :)

**Comment by flobernd** [comment]
Hi there, sorry for not tagging the releases. We planned to do it, but forgot about it. We will check which version of `Zycore` is used in the `Zydis` releases and add tags for these commits.

**Comment by Tachi107** [comment]
> but forgot about it

Don't worry, happens to me all the time :)

Thanks!

**Comment by athre0z** [comment]
[Added it to the version bump checklist](https://github.com/zyantific/zydis/commit/f2429819c5f4d7160f272ec12d8874ef7950912e). Hope we won't forget it next time then!

**Comment by Tachi107** [comment]
I noticed that in https://github.com/zyantific/zycore-c/commit/636bb29945c94ffe4cedb5b6cc797e42c98de3af you bumped the version field in CMakeLists.txt to 1.1.0. I believe that you could tag that commit as the 1.1.0 release, right?

**Comment by flobernd** [comment]
You are correct. I just pushed the tag for this specific commit :-)

**Comment by Tachi107** [comment]
Thanks!

I'm closing this as you tagged the latest release and updated the checklist, but of course feel free to reopen it if you still need to handle something related to this issue.

Thanks again for the collaboration :)
