### ISSUE TITLE
zycore doesn't build on NetBSD

### ISSUE THREAD

**Issue by niclasr** [zyantific/zycore-c#67]
When building zycore on NetBSD it is said to be an unsupported platform.
There are two ways to fix this either do as FreeBSD and check for __NetBSD__
or extend the unix check and check for __unix__ and not just __unix .
I will submit a patch for the latter.

**Comment by flobernd** [comment]
In addition to extending the `unix` check by adding `__unix`, we could probably still add:

```c
#elif defined(__NetBSD__)
#   define ZYAN_NETBSD
#   define ZYAN_UNIX
#   define ZYAN_POSIX
```

after https://github.com/zyantific/zycore-c/blob/master/include/Zycore/Defines.h#L97.

Not sure, if we ever need to specifically check for NetBSD in our compile time macros, but it can't hurt to add, if we are on it already.

**Comment by niclasr** [comment]
OK, if you want that I will add that to.
